CREATE TABLE blog_post
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    body          VARCHAR(255),
    author        VARCHAR(255),
    created_date  TIMESTAMP                               NOT NULL,
    created_by    VARCHAR(255)                            NOT NULL,
    modified_date TIMESTAMP,
    modified_by   VARCHAR(255),
    CONSTRAINT pk_blog PRIMARY KEY (id)
);